'use strict'

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'nzxes',
      [
        {
          symbol: 'ACE',
          price: 0.055,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AFC',
          price: 0.001,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AFI',
          price: 8.26,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AFT',
          price: 3.79,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AGG',
          price: 1.138,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AGL',
          price: 1.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AIA',
          price: 7.915,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AIR',
          price: 0.8,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AKL',
          price: 0.79,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ALD',
          price: 30.5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ALF',
          price: 0.72,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ANZ',
          price: 26.82,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AOF',
          price: 0.139,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'APA',
          price: 2.113,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'APL',
          price: 0.22,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ARB',
          price: 0.22,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ARG',
          price: 1.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ARV',
          price: 1.22,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ASD',
          price: 1.668,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ASF',
          price: 8.12,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ASP',
          price: 1.41,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ASR',
          price: 6.625,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ATM',
          price: 6.5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AUS',
          price: 3.115,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BFG',
          price: 0.325,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BGI',
          price: 0.003,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BGP',
          price: 5.02,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BIF',
          price: 1.45,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BIT',
          price: 1.99,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BLT',
          price: 0.029,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BOT',
          price: 3.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BRM',
          price: 0.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BRMWG',
          price: 0.006,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BRW',
          price: 0.485,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CBD',
          price: 0.3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CCC',
          price: 0.31,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CDI',
          price: 0.82,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CEN',
          price: 7.62,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CHI',
          price: 1.46,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CMO',
          price: 9.65,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CNU',
          price: 8.11,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CO2',
          price: 2.39,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CRP',
          price: 0.24,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CVT',
          price: 3.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'DGL',
          price: 10,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'DIV',
          price: 1.225,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'DOW',
          price: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EBO',
          price: 40.69,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EMF',
          price: 1.294,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EMG',
          price: 2.085,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ENS',
          price: 0.93,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ERD',
          price: 1.28,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ESG',
          price: 2.562,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EUF',
          price: 1.822,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EUG',
          price: 2.626,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EVO',
          price: 0.6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FBU',
          price: 5.17,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FCT',
          price: 18.01,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FNZ',
          price: 3.033,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FPH',
          price: 20.5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FRE',
          price: 10.3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FSF',
          price: 3.16,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FWL',
          price: 1.39,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GBF',
          price: 3.02,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GEN',
          price: 0.057,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GEO',
          price: 0.062,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GFI',
          price: 0.09,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GFL',
          price: 0.47,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GMT',
          price: 2.055,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GNE',
          price: 2.705,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GSH',
          price: 0.035,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GTK',
          price: 1.64,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GWC',
          price: 0.095,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GXH',
          price: 1.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'HFL',
          price: 5.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'HGH',
          price: 1.77,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'HLG',
          price: 5.52,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'IFT',
          price: 8.68,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'IKE',
          price: 0.9,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'IPL',
          price: 1.52,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'JLG',
          price: 0.49,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'JPG',
          price: 8.66,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'JPN',
          price: 1.981,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'KFL',
          price: 1.37,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'KFLWG',
          price: 0.002,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'KMD',
          price: 1.08,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'KPG',
          price: 0.9,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'LIC',
          price: 1.35,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'LIV',
          price: 2.858,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MCK',
          price: 1.95,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MCKPA',
          price: 2.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MCY',
          price: 5.66,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MDZ',
          price: 5.588,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MEE',
          price: 0.013,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MEL',
          price: 4.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MFB',
          price: 0.49,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MFT',
          price: 69.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MHJ',
          price: 1.28,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MHM',
          price: 0.75,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MLN',
          price: 0.96,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MLNWF',
          price: 0.045,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MMH',
          price: 5.98,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MNW',
          price: 5.04,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MOV',
          price: 1.11,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MPG',
          price: 0.205,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MWE',
          price: 0.187,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MZY',
          price: 9.59,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NGB',
          price: 2.163,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NPF',
          price: 1.191,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NPH',
          price: 2.78,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NTL',
          price: 0.002,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NWF',
          price: 0.161,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZA',
          price: 0.36,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZB',
          price: 2.866,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZC',
          price: 2.98,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZG',
          price: 2.385,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZK',
          price: 0.25,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZL',
          price: 1.07,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZM',
          price: 1.19,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZO',
          price: 0.425,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZX',
          price: 1.22,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'OCA',
          price: 0.8,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'OZY',
          price: 4.499,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PCT',
          price: 1.24,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PEB',
          price: 0.485,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PFI',
          price: 2.38,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PGW',
          price: 4.16,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PHL',
          price: 0.001,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PLP',
          price: 1.29,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'POT',
          price: 6.26,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PPH',
          price: 1.28,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PYS',
          price: 0.315,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'RAD',
          price: 0.31,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'RAK',
          price: 1.26,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'RBD',
          price: 7.05,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'RUA',
          price: 0.25,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'RYM',
          price: 7.62,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SAN',
          price: 4.17,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SCL',
          price: 4.56,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SCT',
          price: 2.71,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SCY',
          price: 0.14,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SDL',
          price: 2.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SEK',
          price: 3.49,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SKC',
          price: 2.83,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SKL',
          price: 5.64,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SKO',
          price: 2.6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SKT',
          price: 2.268,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SML',
          price: 2.93,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SNC',
          price: 0.006,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SPG',
          price: 1.6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SPK',
          price: 5.12,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SPN',
          price: 8.3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SPY',
          price: 0.925,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'STU',
          price: 1.3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SUM',
          price: 9.74,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SVR',
          price: 0.405,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TAH',
          price: 1.9,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TCL',
          price: 7.74,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TEM',
          price: 2.83,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TGG',
          price: 2.58,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'THL',
          price: 3.47,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TNZ',
          price: 1.85,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TRA',
          price: 3.55,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TRU',
          price: 0.044,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TSK',
          price: 0.335,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TWF',
          price: 2.867,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TWH',
          price: 2.914,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TWL',
          price: 0.65,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TWR',
          price: 0.675,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USA',
          price: 2.924,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USF',
          price: 11.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USG',
          price: 7.048,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USM',
          price: 6.698,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USS',
          price: 6.066,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USV',
          price: 4.601,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VCT',
          price: 4.15,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VGL',
          price: 1.52,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VHP',
          price: 2.385,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VNT',
          price: 2.8,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VSL',
          price: 8.39,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VTL',
          price: 0.34,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'WBC',
          price: 25.81,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'WHS',
          price: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'WIN',
          price: 2.19,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    )
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete(
      'nzxes',
      [
        {
          symbol: 'ACE',
          price: 0.055,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AFC',
          price: 0.001,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AFI',
          price: 8.26,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AFT',
          price: 3.79,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AGG',
          price: 1.138,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AGL',
          price: 1.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AIA',
          price: 7.915,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AIR',
          price: 0.8,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AKL',
          price: 0.79,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ALD',
          price: 30.5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ALF',
          price: 0.72,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ANZ',
          price: 26.82,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AOF',
          price: 0.139,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'APA',
          price: 2.113,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'APL',
          price: 0.22,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ARB',
          price: 0.22,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ARG',
          price: 1.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ARV',
          price: 1.22,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ASD',
          price: 1.668,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ASF',
          price: 8.12,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ASP',
          price: 1.41,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ASR',
          price: 6.625,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ATM',
          price: 6.5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'AUS',
          price: 3.115,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BFG',
          price: 0.325,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BGI',
          price: 0.003,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BGP',
          price: 5.02,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BIF',
          price: 1.45,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BIT',
          price: 1.99,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BLT',
          price: 0.029,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BOT',
          price: 3.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BRM',
          price: 0.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BRMWG',
          price: 0.006,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'BRW',
          price: 0.485,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CBD',
          price: 0.3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CCC',
          price: 0.31,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CDI',
          price: 0.82,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CEN',
          price: 7.62,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CHI',
          price: 1.46,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CMO',
          price: 9.65,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CNU',
          price: 8.11,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CO2',
          price: 2.39,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CRP',
          price: 0.24,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'CVT',
          price: 3.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'DGL',
          price: 10,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'DIV',
          price: 1.225,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'DOW',
          price: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EBO',
          price: 40.69,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EMF',
          price: 1.294,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EMG',
          price: 2.085,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ENS',
          price: 0.93,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ERD',
          price: 1.28,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'ESG',
          price: 2.562,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EUF',
          price: 1.822,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EUG',
          price: 2.626,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'EVO',
          price: 0.6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FBU',
          price: 5.17,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FCT',
          price: 18.01,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FNZ',
          price: 3.033,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FPH',
          price: 20.5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FRE',
          price: 10.3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FSF',
          price: 3.16,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'FWL',
          price: 1.39,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GBF',
          price: 3.02,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GEN',
          price: 0.057,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GEO',
          price: 0.062,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GFI',
          price: 0.09,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GFL',
          price: 0.47,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GMT',
          price: 2.055,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GNE',
          price: 2.705,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GSH',
          price: 0.035,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GTK',
          price: 1.64,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GWC',
          price: 0.095,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'GXH',
          price: 1.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'HFL',
          price: 5.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'HGH',
          price: 1.77,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'HLG',
          price: 5.52,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'IFT',
          price: 8.68,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'IKE',
          price: 0.9,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'IPL',
          price: 1.52,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'JLG',
          price: 0.49,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'JPG',
          price: 8.66,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'JPN',
          price: 1.981,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'KFL',
          price: 1.37,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'KFLWG',
          price: 0.002,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'KMD',
          price: 1.08,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'KPG',
          price: 0.9,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'LIC',
          price: 1.35,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'LIV',
          price: 2.858,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MCK',
          price: 1.95,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MCKPA',
          price: 2.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MCY',
          price: 5.66,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MDZ',
          price: 5.588,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MEE',
          price: 0.013,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MEL',
          price: 4.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MFB',
          price: 0.49,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MFT',
          price: 69.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MHJ',
          price: 1.28,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MHM',
          price: 0.75,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MLN',
          price: 0.96,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MLNWF',
          price: 0.045,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MMH',
          price: 5.98,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MNW',
          price: 5.04,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MOV',
          price: 1.11,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MPG',
          price: 0.205,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MWE',
          price: 0.187,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'MZY',
          price: 9.59,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NGB',
          price: 2.163,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NPF',
          price: 1.191,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NPH',
          price: 2.78,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NTL',
          price: 0.002,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NWF',
          price: 0.161,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZA',
          price: 0.36,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZB',
          price: 2.866,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZC',
          price: 2.98,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZG',
          price: 2.385,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZK',
          price: 0.25,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZL',
          price: 1.07,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZM',
          price: 1.19,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZO',
          price: 0.425,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'NZX',
          price: 1.22,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'OCA',
          price: 0.8,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'OZY',
          price: 4.499,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PCT',
          price: 1.24,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PEB',
          price: 0.485,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PFI',
          price: 2.38,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PGW',
          price: 4.16,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PHL',
          price: 0.001,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PLP',
          price: 1.29,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'POT',
          price: 6.26,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PPH',
          price: 1.28,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'PYS',
          price: 0.315,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'RAD',
          price: 0.31,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'RAK',
          price: 1.26,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'RBD',
          price: 7.05,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'RUA',
          price: 0.25,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'RYM',
          price: 7.62,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SAN',
          price: 4.17,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SCL',
          price: 4.56,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SCT',
          price: 2.71,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SCY',
          price: 0.14,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SDL',
          price: 2.2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SEK',
          price: 3.49,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SKC',
          price: 2.83,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SKL',
          price: 5.64,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SKO',
          price: 2.6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SKT',
          price: 2.268,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SML',
          price: 2.93,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SNC',
          price: 0.006,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SPG',
          price: 1.6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SPK',
          price: 5.12,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SPN',
          price: 8.3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SPY',
          price: 0.925,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'STU',
          price: 1.3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SUM',
          price: 9.74,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'SVR',
          price: 0.405,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TAH',
          price: 1.9,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TCL',
          price: 7.74,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TEM',
          price: 2.83,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TGG',
          price: 2.58,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'THL',
          price: 3.47,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TNZ',
          price: 1.85,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TRA',
          price: 3.55,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TRU',
          price: 0.044,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TSK',
          price: 0.335,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TWF',
          price: 2.867,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TWH',
          price: 2.914,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TWL',
          price: 0.65,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'TWR',
          price: 0.675,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USA',
          price: 2.924,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USF',
          price: 11.7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USG',
          price: 7.048,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USM',
          price: 6.698,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USS',
          price: 6.066,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'USV',
          price: 4.601,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VCT',
          price: 4.15,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VGL',
          price: 1.52,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VHP',
          price: 2.385,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VNT',
          price: 2.8,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VSL',
          price: 8.39,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'VTL',
          price: 0.34,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'WBC',
          price: 25.81,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'WHS',
          price: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          symbol: 'WIN',
          price: 2.19,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    )
  },
}
